import { useState } from 'react';
import { RotateCcw, Sparkles } from 'lucide-react';
import type { Insight } from '../../lib/types';
import { CURRENT_MONTH, monthLabel } from '../../lib/format';
import { errorMessage } from '../../lib/api';
import { useStore } from '../../lib/store';
import { PageHeader } from '../../components/PageHeader';
import { Button } from '../../components/ui/Button';
import { Badge, EmptyState, Modal, Skeleton } from '../../components/ui/Feedback';
import { Card } from '../../components/ui/Card';
import { InsightCard } from '../../components/Finance';

export default function Insights() {
  const { insights, cat, toast, generateInsight, transactions } = useStore();
  const monthName = monthLabel(CURRENT_MONTH, true).split(' ')[0];
  const count = transactions.filter((t) => t.date.startsWith(CURRENT_MONTH)).length;
  const refresh = async () => {
    setGenerating(true);
    try {
      await generateInsight();
      toast(`Your ${monthName} insight is up to date.`, 'info');
    } catch (e) {
      toast(errorMessage(e), 'error');
    }
    setGenerating(false);
  };
  const [viewing, setViewing] = useState<Insight | null>(null);
  const [generating, setGenerating] = useState(false);
  const [current, ...archive] = insights;

  return (
    <div className="space-y-6">
      <PageHeader title="AI Insights" subtitle="Each month, Campus Coin AI reads your spending and explains it in plain words, with one small thing to try."
        actions={<Button variant="ai" loading={generating} icon={<RotateCcw className="h-4 w-4" />}
          onClick={refresh}>
          {current?.month === CURRENT_MONTH ? 'Refresh this month' : `Write my ${monthName} insight`}
        </Button>} />

      <section aria-label="This month">
        {generating ? (
          <div className="rounded-card border border-lavender/40 bg-lavender-soft/50 p-6 dark:bg-lavender/[.06]">
            <p className="flex items-center gap-2 text-sm font-bold text-ai"><Sparkles className="h-4 w-4 animate-pulse" /> Reading {count} transactions from {monthName}…</p>
            <Skeleton className="mt-4 h-6 w-3/4" /><Skeleton className="mt-3 h-4 w-1/2" /><Skeleton className="mt-6 h-20" />
          </div>
        ) : current ? <InsightCard insight={current} featured onView={() => setViewing(current)} />
          : <Card><EmptyState title="No insights yet" body="Log at least three expenses this month, then tap the button above. Campus Coin AI will explain your month in plain words." /></Card>}
      </section>

      {archive.length > 0 && <section aria-label="Past insights">
        <h2 className="mb-4 text-lg font-bold">Previous months</h2>
        <div className="grid gap-5 md:grid-cols-2">
          {archive.map((i) => <InsightCard key={i.id} insight={i} onView={() => setViewing(i)} />)}
        </div>
      </section>}

      <Modal open={!!viewing} onClose={() => setViewing(null)} title={viewing ? `${monthLabel(viewing.month, true)} summary` : ''} subtitle="Generated by Campus Coin AI">
        {viewing && (
          <div className="space-y-4">
            <div><p className="text-xs font-bold text-muted">Summary</p><p className="mt-1">{viewing.summary}</p></div>
            <div><p className="text-xs font-bold text-muted">Notable pattern</p><p className="mt-1">{viewing.pattern}</p>
              <Badge tone={viewing.change > 0 ? 'neg' : 'pos'} className="mt-2">{cat(viewing.categoryId)?.name ?? 'Top category'} {viewing.change > 0 ? '+' : ''}{viewing.change}% vs your average</Badge></div>
            <div className="rounded-2xl bg-lavender-soft/70 p-4 dark:bg-lavender/10"><p className="text-xs font-bold text-ai">Suggested action</p><p className="mt-1 font-semibold">{viewing.action}</p></div>
          </div>
        )}
      </Modal>
    </div>
  );
}
